# BlindChase configuration file

# ################################# #
# LICENSE NOTICE                    #
# copyright                         #
#   All right reserved Yui-KITAMURA #
# ################################# #
# Check GitHub @yui-Kitamura        #
# ################################# #

resourcePack:
  github:
    user: yui-Kitamura
    repo: BlindChase
  # network
  timeoutSec: 10
  retries: 2
