# BlindChase configuration file

# ################################# #
# LICENSE NOTICE                    #
# copyright                         #
#   All right reserved Yui-KITAMURA #
# ################################# #
# Check GitHub @yui-Kitamura        #
# ################################# #

